### ISSUE TITLE
Implement `browsingContext.captureScreenshot` command

### ISSUE THREAD

**Issue by sadym-chromium** [GoogleChromeLabs/chromium-bidi#78] opened 2021-12-07 14:09 UTC
https://w3c.github.io/webdriver-bidi/#command-browsingContext-captureScreenshot

**Comment by thiagowfx** [comment] 2023-03-17 19:26
Closing this as a duplicate of https://github.com/GoogleChromeLabs/chromium-bidi/issues/514.

**Closed by thiagowfx** 2023-03-17 19:26 UTC
Labels: implementation
