### ISSUE TITLE
Support `destination` and `initiatorType` in Network.Request

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#2824] opened 2024-11-26 12:54 UTC
Currently we only provide empty values. We should be able to provide better information based on what we have or update CDP to support this case.

**Comment by OrKoN** [comment] 2024-11-26 13:30
Duplicate of https://github.com/GoogleChromeLabs/chromium-bidi/issues/2776

**Closed by OrKoN** 2024-11-26 13:30 UTC
