### ISSUE TITLE
No `log.entryAdded` on navigation to page that throws error

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#564] opened 2023-03-22 15:17 UTC
In Puppeteer we have the following test ([here](https://github.com/puppeteer/puppeteer/blob/main/test/src/page.spec.ts#L1341)). 
We set up a listener for exceptions (`log.entryAdded`) , then we navigate to a page that throws error once loaded. 
What happens is the event is never send back to Puppeteer, in my investigation we are getting the error from CDP but we are not resolving the realm correctly (its `undefined` - [line](https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/src/bidiMapper/domains/log/logManager.ts#L135)), then it's not send back as we subscribe only on the BrowsingContext level.

**Comment by sadym-chromium** [comment] 2023-04-25 08:07
I guess the same root cause as https://github.com/GoogleChromeLabs/chromium-bidi/issues/620, as not reproducible anymore.

**Comment by sadym-chromium** [comment] 2023-04-25 08:11
Can confirm the test is failing on https://github.com/puppeteer/puppeteer/commit/e5d686405623488e808b9aaf85083fb24f0894fa and passing on the next https://github.com/puppeteer/puppeteer/commit/513f65898909535486d0c30a3be1d753fe227abf. Closing.

**Closed by sadym-chromium** 2023-04-25 08:11 UTC
Labels: bug
