### ISSUE TITLE
Network events produce non-spec compliant JSON payload

### ISSUE THREAD

**Issue by jimevans** [GoogleChromeLabs/chromium-bidi#1618] opened 2023-12-12 15:25 UTC
Listening for events in the `network` module contain JSON payloads that do not comply with the spec. In particular, the `headersSize` property value of the `request` object is set to `-1`, which is defined in the spec as a `js-uint`, precluding negative values. A sample payload:

```json
{
    "method": "network.responseCompleted",
    "params": {
        "context": "04B73FBC32AC72D9A791E6B72D79488C",
        "navigation": "6EE1B5F354BCA2F13FBBD0FDEA4E9A3C",
        "redirectCount": 0,
        "request": {
            "request": "6EE1B5F354BCA2F13FBBD0FDEA4E9A3C",
            "url": "http://localhost:52509/",
            "method": "GET",
            "headers": [
                {
                    "name": "Upgrade-Insecure-Requests",
                    "value": {
                        "type": "string",
                        "value": "1"
                    }
                },
                {
                    "name": "User-Agent",
                    "value": {
                        "type": "string",
                        "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
                    }
                },
                {
                    "name": "sec-ch-ua",
                    "value": {
                        "type": "string",
                        "value": "\"Google Chrome\";v=\"119\", \"Chromium\";v=\"119\", \"Not?A_Brand\";v=\"24\""
                    }
                },
                {
                    "name": "sec-ch-ua-mobile",
                    "value": {
                        "type": "string",
                        "value": "?0"
                    }
                },
                {
                    "name": "sec-ch-ua-platform",
                    "value": {
                        "type": "string",
                        "value": "\"macOS\""
                    }
                }
            ],
            "cookies": [],
            "headersSize": -1,
            "bodySize": 0,
            "timings": {
                "timeOrigin": 0,
                "requestTime": 0,
                "redirectStart": 0,
                "redirectEnd": 0,
                "fetchStart": 0,
                "dnsStart": 0,
                "dnsEnd": 0,
                "connectStart": 0,
                "connectEnd": 0,
                "tlsStart": 0,
                "requestStart": 0,
                "responseStart": 0,
                "responseEnd": 0
            }
        },
        "timestamp": 1702393845589,
        "response": {
            "url": "http://localhost:52509/index.html",
            "protocol": "http/1.1",
            "status": 301,
            "statusText": "OK",
            "fromCache": false,
            "headers": [
                {
                    "name": "Connection",
                    "value": {
                        "type": "string",
                        "value": "keep-alive"
                    }
                },
                {
                    "name": "Content-Length",
                    "value": {
                        "type": "string",
                        "value": "654"
                    }
                },
                {
                    "name": "Content-Type",
                    "value": {
                        "type": "string",
                        "value": "text/html;charset=utf-8"
                    }
                },
                {
                    "name": "Date",
                    "value": {
                        "type": "string",
                        "value": "Tue, 12 Dec 2023 15:10:45 G12T"
                    }
                },
                {
                    "name": "Server",
                    "value": {
                        "type": "string",
                        "value": "PinchHitter/0.1 .NET/6.0"
                    }
                }
            ],
            "mimeType": "text/html",
            "bytesReceived": 175,
            "headersSize": 156,
            "bodySize": 0,
            "content": {
                "size": 0
            }
        }
    },
    "type": "event",
    "channel": "/2/nochan/bidi"
}
```

**Comment by Lightning00Blade** [comment] 2024-01-17 14:09
@jimevans could you provide a page/html or repo that this can be observed?  The last changes in https://github.com/GoogleChromeLabs/chromium-bidi/pull/1498 should return the expected value defined in BiDi's CDDL.

**Comment by Lightning00Blade** [comment] 2024-04-08 11:00
Closing as complete as I can't reproduce the issue anymore and there was no provided repo.

**Closed by Lightning00Blade** 2024-04-08 11:00 UTC
