### ISSUE TITLE
test_remove_intercept_unblocks is flaky

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#2027] opened 2024-03-19 14:46 UTC
See https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/8344865962/job/22838354837?pr=2026

cc @Lightning00Blade

**Comment by Lightning00Blade** [comment] 2024-03-19 15:35
@sadym-chromium There seems to be a regression with the latest changes in test runner. I can't see CDP logs for the E2E failures when I download the logs. Could you please investigate or tell me if you can't?

**Comment by sadym-chromium** [comment] 2024-03-19 15:46
ack

**Comment by sadym-chromium** [comment] 2024-03-19 15:56
> @sadym-chromium There seems to be a regression with the latest changes in test runner. I can't see CDP logs for the E2E failures when I download the logs. Could you please investigate or tell me if you can't?

https://github.com/GoogleChromeLabs/chromium-bidi/pull/2029

**Comment by Lightning00Blade** [comment] 2024-08-08 14:30
I have not seen this E2E test flake now, closing.

**Closed by Lightning00Blade** 2024-08-08 14:30 UTC
Labels: test flakiness, P2
